"""
modules/report_generator.py — PDF & JSON Report Generator
Generates a professional security assessment report using fpdf2 and Python file I/O.
"""
import json
import logging
import os
from datetime import datetime
from typing import Dict, Any, List

from fpdf import FPDF, XPos, YPos
import config
from modules.risk_scorer import get_risk_label

logger = logging.getLogger("assessor.report")

# ─────────────────────────────────────────────────────────────────────────────
#  Color Palette
# ─────────────────────────────────────────────────────────────────────────────
COL_BG_DARK     = (15,  23,  42)     # Deep navy
COL_BG_MID      = (30,  41,  59)     # Card background
COL_ACCENT      = (99,  102, 241)    # Indigo accent
COL_WHITE       = (255, 255, 255)
COL_LIGHT_GRAY  = (241, 245, 249)
COL_MID_GRAY    = (148, 163, 184)
COL_TEXT_DARK   = (15,  23,  42)
COL_TEXT_LIGHT  = (226, 232, 240)

SEV_COLORS = {
    "CRITICAL": (220, 38,  38),
    "HIGH":     (234, 88,  12),
    "MEDIUM":   (202, 138, 4),
    "LOW":      (37,  99,  235),
    "INFO":     (100, 116, 139),
}

SEV_BG = {
    "CRITICAL": (255, 220, 220),
    "HIGH":     (255, 237, 213),
    "MEDIUM":   (254, 249, 195),
    "LOW":      (219, 234, 254),
    "INFO":     (241, 245, 249),
}


# ─────────────────────────────────────────────────────────────────────────────
#  Custom FPDF class
# ─────────────────────────────────────────────────────────────────────────────
class SecurityReport(FPDF):
    def __init__(self, target_url: str, scan_date: str):
        super().__init__()
        self.target_url = target_url
        self.scan_date  = scan_date
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)

    def header(self):
        if self.page_no() == 1:
            return
        # ── Running header ─────────────────────────────────────────────
        self.set_fill_color(*COL_BG_DARK)
        self.rect(0, 0, 210, 12, "F")
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*COL_TEXT_LIGHT)
        self.set_xy(10, 3)
        self.cell(0, 6, "SECURITY ASSESSMENT REPORT", align="L")
        self.set_xy(0, 3)
        self.cell(200, 6, f"Page {self.page_no()}", align="R")
        self.set_text_color(*COL_TEXT_DARK)
        self.ln(14)

    def footer(self):
        if self.page_no() == 1:
            return
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*COL_MID_GRAY)
        self.cell(0, 5, f"Target: {self.target_url}  |  {self.scan_date}  |  "
                        f"Generated by {config.REPORT_AUTHOR}", align="C")


# ─────────────────────────────────────────────────────────────────────────────
#  Main generation function
# ─────────────────────────────────────────────────────────────────────────────
def generate_report(
    url: str,
    scan_results: Dict[str, Any],
    risk_summary: Dict[str, Any],
    findings: List[Dict],
    output_dir: str,
    timestamp: str,
) -> Dict[str, str]:
    """
    Generate PDF and TXT reports.

    Returns:
        {"pdf": "...", "txt": "..."}
    """
    os.makedirs(output_dir, exist_ok=True)

    from urllib.parse import urlparse
    import re
    parsed = urlparse(url)
    host   = parsed.hostname or "target"
    host_clean = re.sub(r"[^\w.-]", "_", host)
    port_str   = f"_port{parsed.port}" if parsed.port else ""
    base_name  = f"report_{host_clean}{port_str}_{timestamp}"

    pdf_path = os.path.join(output_dir, f"{base_name}.pdf")
    txt_path = os.path.join(output_dir, f"{base_name}.txt")

    scan_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # -- TXT Report
    _save_txt_report(txt_path, url, scan_date, risk_summary, findings, scan_results)

    # -- PDF Report
    _save_pdf_report(pdf_path, url, scan_date, risk_summary, findings, scan_results)

    logger.info(f"Reports saved: {pdf_path}, {txt_path}")
    return {"pdf": pdf_path, "txt": txt_path}




# ─────────────────────────────────────────────────────────────────────────────
#  TXT report
# ─────────────────────────────────────────────────────────────────────────────
def _save_txt_report(path, url, date, risk_summary, findings, scan_results):
    """Generate a structured plain-text report readable in any terminal/editor."""
    SEP  = "=" * 70
    SEP2 = "-" * 70
    lines = []

    # ── Header ──────────────────────────────────────────────────────────────
    lines += [
        SEP,
        "  AUTOMATED SECURITY MISCONFIGURATION ASSESSMENT REPORT",
        f"  {config.REPORT_AUTHOR}  v{config.REPORT_VERSION}",
        SEP,
        f"  Target URL  : {url}",
        f"  Scan Date   : {date}",
        SEP,
        "",
    ]

    # ── Overall Risk Score ───────────────────────────────────────────────────
    max_score     = risk_summary.get("max_score", 0.0)
    overall_sev   = risk_summary.get("max_severity", "INFO")
    risk_label    = get_risk_label(max_score)
    counts        = risk_summary.get("counts", {})
    total         = sum(counts.values())
    total_risks   = risk_summary.get("total_risks", 0)

    lines += [
        "[OVERALL RISK ASSESSMENT]",
        SEP2,
        f"  Max CVSS Score     : {max_score:.1f} / 10",
        f"  Overall Risk Level : {risk_label.upper()}",
        f"  Total Findings     : {total}",
        f"  Total Risks        : {total_risks} (Excluding INFO)",
        "",
        "  Severity Breakdown:",
    ]
    severity_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    max_count = max((counts.get(s, 0) for s in severity_order), default=1) or 1
    for sev in severity_order:
        count   = counts.get(sev, 0)
        bar_len = int((count / max_count) * 30) if count > 0 else 0
        bar     = "|" * bar_len
        lines.append(f"    {sev:<10} {count:>4}  [{bar:<30}]")
    lines += ["", ""]

    # -- Scan Module Status
    lines += [
        "[SCAN MODULE STATUS]",
        SEP2,
    ]
    for tool_name, data in scan_results.items():
        status       = data.get("status", "unknown")
        n_findings   = len(data.get("findings", []))
        error_reason = data.get("error_reason", "")

        # Extract reason from raw_output if not set
        if status != "success" and not error_reason:
            raw = data.get("raw_output", "")
            if raw and raw.strip():
                error_reason = raw.strip().splitlines()[-1][:100]

        if status == "success":
            icon   = "[OK]   "
            detail = f"Findings: {n_findings}"
        elif status == "error":
            icon   = "[ERROR]"
            detail = f"FAILED  -- {error_reason}" if error_reason else "FAILED"
        elif status == "timeout":
            icon   = "[TMO]  "
            detail = f"TIMEOUT -- ran longer than allowed"
        else:
            icon   = "[???]  "
            detail = status

        lines.append(f"  {icon}  {tool_name.upper():<12} {detail}")

        # Extra per-tool info (only on success)
        if status == "success":
            if tool_name == "nmap" and data.get("open_ports"):
                ports_str = ", ".join(map(str, data["open_ports"]))
                lines.append(f"             Open Ports  : {ports_str}")
            if tool_name == "whatweb" and data.get("technologies"):
                techs = ", ".join(
                    f"{t['name']}{(' v' + t['version']) if t.get('version') else ''}"
                    for t in data["technologies"][:6]
                )
                lines.append(f"             Technologies: {techs}")
            if tool_name == "gobuster" and data.get("paths"):
                lines.append(f"             Paths Found : {len(data['paths'])}")
    lines += ["", ""]


    # ── Detailed Findings ────────────────────────────────────────────────────
    lines += [
        "[DETAILED FINDINGS]",
        SEP2,
    ]

    if not findings:
        lines.append("  No findings recorded.")
    else:
        groups = {s: [] for s in severity_order}
        for f in findings:
            sev = f.get("severity", "INFO").upper()
            groups.get(sev, groups["INFO"]).append(f)

        finding_num = 1
        for sev_name in severity_order:
            group = groups[sev_name]
            if not group:
                continue
            lines += [
                "",
                f"  >> {sev_name} ({len(group)} finding(s))",
                "  " + "-" * 60,
            ]
            for f in group:
                score    = f.get("cvss_base_score", 0.0)
                title    = f.get("title", "Unknown")
                tool     = f.get("tool", "").upper()
                category = f.get("category", "")
                desc     = f.get("description", "")
                evidence = f.get("evidence", "")
                vector   = f.get("cvss_vector", "")
                cve      = f.get("cve", "")

                lines += [
                    f"  [{finding_num:03d}] {title}",
                    f"       Severity : {sev_name}  |  CVSS Score: {score:.1f}",
                    f"       Tool     : {tool}  |  Category: {category}",
                ]
                if cve:
                    lines.append(f"       CVE      : {cve}")
                if desc:
                    # Wrap long descriptions
                    desc_lines = _wrap_text(desc, width=60, prefix="       ")
                    lines.append(f"       Desc     : {desc_lines[0].strip()}")
                    for dl in desc_lines[1:]:
                        lines.append(dl)
                if evidence:
                    ev_short = evidence[:100] + ("..." if len(evidence) > 100 else "")
                    lines.append(f"       Evidence : {ev_short}")
                if vector:
                    lines.append(f"       CVSS Vec : {vector}")
                lines.append("")
                finding_num += 1

    lines += [""]

    # ── Footer ───────────────────────────────────────────────────────────────
    lines += [
        SEP,
        "  DISCLAIMER: This report is generated by an automated scanning system.",
        "  Results may contain false positives. Verify all findings before remediation.",
        "  For authorized security testing purposes only.",
        SEP,
        "",
    ]

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def _wrap_text(text: str, width: int = 60, prefix: str = "") -> list:
    """Simple word-wrap for text in TXT report."""
    words = text.split()
    wrapped_lines = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 <= width:
            current = (current + " " + word).strip()
        else:
            if current:
                wrapped_lines.append(prefix + current)
            current = word
    if current:
        wrapped_lines.append(prefix + current)
    return wrapped_lines or [prefix]


# ─────────────────────────────────────────────────────────────────────────────
#  PDF report
# ─────────────────────────────────────────────────────────────────────────────
def _save_pdf_report(pdf_path, url, date, risk_summary, findings, scan_results):
    pdf = SecurityReport(url, date)
    pdf.add_page()

    # Page 1: Cover
    _draw_cover(pdf, url, date, risk_summary)

    # Page 2: Executive Summary
    pdf.add_page()
    _draw_exec_summary(pdf, url, risk_summary, findings, scan_results)

    # Page 3+: Findings
    if findings:
        pdf.add_page()
        _draw_findings_section(pdf, findings)

    # Last page: Appendix (tool status)
    pdf.add_page()
    _draw_appendix(pdf, scan_results, risk_summary)

    pdf.output(pdf_path)


# ─────────────────────────────────────────────────────────────────────────────
#  Cover Page
# ─────────────────────────────────────────────────────────────────────────────
def _draw_cover(pdf: SecurityReport, url: str, date: str, risk_summary: Dict):
    # Full-page dark background
    pdf.set_fill_color(*COL_BG_DARK)
    pdf.rect(0, 0, 210, 297, "F")

    # Accent bar top
    pdf.set_fill_color(*COL_ACCENT)
    pdf.rect(0, 0, 210, 5, "F")

    # Accent bar bottom
    pdf.set_fill_color(*COL_ACCENT)
    pdf.rect(0, 292, 210, 5, "F")

    # ── Report Title ─────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(*COL_TEXT_LIGHT)
    pdf.set_y(50)
    pdf.cell(0, 14, "SECURITY ASSESSMENT", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 14, "REPORT", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Subtitle
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(*COL_MID_GRAY)
    pdf.set_y(84)
    pdf.cell(0, 8, "Automated Security Misconfiguration Assessment", align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 8, "& Auditing System for Web Applications", align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Divider line
    pdf.set_draw_color(*COL_ACCENT)
    pdf.set_line_width(0.8)
    pdf.line(50, 107, 160, 107)

    # ── Target Info ───────────────────────────────────────────────────────
    pdf.set_y(115)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*COL_MID_GRAY)
    pdf.cell(0, 6, "TARGET URL", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*COL_TEXT_LIGHT)
    _center_text_safe(pdf, url, 13)

    pdf.set_y(135)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*COL_MID_GRAY)
    pdf.cell(0, 6, "SCAN DATE", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*COL_TEXT_LIGHT)
    pdf.cell(0, 7, date, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Risk Level Banner (No numeric score) ─────────────────────────────
    max_score   = risk_summary.get("max_score", 0.0)
    overall_sev = risk_summary.get("max_severity", "INFO")
    risk_label  = get_risk_label(max_score)
    sev_color   = SEV_COLORS.get(overall_sev, (100, 116, 139))

    badge_x, badge_y, badge_w, badge_h = 60, 158, 90, 22
    pdf.set_fill_color(*COL_BG_MID)
    pdf.rect(badge_x, badge_y, badge_w, badge_h, "F")

    # Accent left border
    pdf.set_fill_color(*sev_color)
    pdf.rect(badge_x, badge_y, 4, badge_h, "F")

    # Risk level text
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*sev_color)
    pdf.set_xy(badge_x + 4, badge_y + 6)
    pdf.cell(badge_w - 4, 10, risk_label.upper(), align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Severity Counts ────────────────────────────────────────────────────
    counts = risk_summary.get("counts", {})
    severities = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    box_w = 34
    start_x = (210 - (box_w * len(severities))) / 2
    y_start = 205

    for i, sev in enumerate(severities):
        bx = start_x + i * box_w
        sev_col = SEV_COLORS.get(sev, (100, 116, 139))
        count   = counts.get(sev, 0)

        # Box background
        pdf.set_fill_color(*COL_BG_MID)
        pdf.rect(bx, y_start, box_w - 2, 28, "F")
        # Top color bar
        pdf.set_fill_color(*sev_col)
        pdf.rect(bx, y_start, box_w - 2, 3, "F")

        # Count
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(*sev_col)
        pdf.set_xy(bx, y_start + 4)
        pdf.cell(box_w - 2, 12, str(count), align="C",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Label
        pdf.set_font("Helvetica", "", 7)
        pdf.set_text_color(*COL_MID_GRAY)
        pdf.set_xy(bx, y_start + 17)
        pdf.cell(box_w - 2, 8, sev, align="C",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Footer
    pdf.set_y(265)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*COL_MID_GRAY)
    pdf.cell(0, 6, config.REPORT_AUTHOR, align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, f"Version {config.REPORT_VERSION}", align="C")


def _center_text_safe(pdf, text, size=11):
    """Print centered text, truncating if too long."""
    max_chars = 65
    if len(text) > max_chars:
        text = text[:max_chars - 3] + "..."
    pdf.cell(0, 8, text, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)


# ─────────────────────────────────────────────────────────────────────────────
#  Executive Summary Page
# ─────────────────────────────────────────────────────────────────────────────
def _draw_exec_summary(pdf, url, risk_summary, findings, scan_results):
    _section_header(pdf, "EXECUTIVE SUMMARY")

    counts    = risk_summary.get("counts", {})
    total     = sum(counts.values())
    total_risks = risk_summary.get("total_risks", 0)
    max_score = risk_summary.get("max_score", 0.0)
    # Summary text
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*COL_TEXT_DARK)
    summary_text = (
        f"An automated security assessment was conducted against the target: {url}. "
        f"The scan identified a total of {total} security findings across all scan modules, "
        f"representing {total_risks} distinct security risks (excluding INFO-level observations). "
        f"The maximum CVSS score identified is {max_score:.1f}/10, classified as {get_risk_label(max_score)}. "
        f"Immediate attention is required for any CRITICAL and HIGH severity findings."
    )
    pdf.multi_cell(0, 6, summary_text)
    pdf.ln(5)

    # Risk breakdown chart
    _section_subheader(pdf, "Finding Distribution")
    severities = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    bar_max_w  = 120
    max_count  = max((counts.get(s, 0) for s in severities), default=1) or 1

    for sev_name in severities:
        count   = counts.get(sev_name, 0)
        sev_col = SEV_COLORS.get(sev_name, (100, 116, 139))
        bar_w   = int((count / max_count) * bar_max_w) if count > 0 else 2

        # Severity label
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*sev_col)
        pdf.set_x(20)
        pdf.cell(22, 7, sev_name, align="L")

        # Bar
        pdf.set_fill_color(*sev_col)
        pdf.rect(pdf.get_x(), pdf.get_y() + 1, bar_w, 5, "F")

        # Count
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*COL_TEXT_DARK)
        pdf.set_x(pdf.get_x() + bar_w + 3)
        pdf.cell(15, 7, str(count), align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(4)

    # Tools used
    _section_subheader(pdf, "Scan Modules")
    tool_statuses = []
    for tool, data in scan_results.items():
        status = data.get("status", "unknown")
        icon   = "[OK]" if status == "success" else ("[ERR]" if status == "error" else "[TMO]")
        tool_statuses.append(f"{icon} {tool.upper()}: {status.capitalize()}")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*COL_TEXT_DARK)
    for i in range(0, len(tool_statuses), 2):
        left = tool_statuses[i]
        right = tool_statuses[i + 1] if i + 1 < len(tool_statuses) else ""
        pdf.set_x(20)
        pdf.cell(85, 6, left)
        pdf.cell(85, 6, right, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(5)

    # Risk score visual gauge
    _section_subheader(pdf, "Max CVSS Score")
    _draw_score_gauge(pdf, max_score,
                      risk_summary.get("max_severity", "INFO"))


def _draw_score_gauge(pdf, score, severity):
    """Draw a horizontal risk gauge."""
    gauge_x, gauge_y = 20, pdf.get_y() + 2
    gauge_w, gauge_h = 170, 12

    # Background bar
    pdf.set_fill_color(*COL_LIGHT_GRAY)
    pdf.rect(gauge_x, gauge_y, gauge_w, gauge_h, "F")

    # Filled portion
    fill_w = int((score / 10.0) * gauge_w)
    sev_col = SEV_COLORS.get(severity, (100, 116, 139))
    if fill_w > 0:
        pdf.set_fill_color(*sev_col)
        pdf.rect(gauge_x, gauge_y, fill_w, gauge_h, "F")

    # Score label inside bar
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*COL_WHITE)
    if fill_w > 20:
        pdf.set_xy(gauge_x + 4, gauge_y + 2)
        label = get_risk_label(score)
        pdf.cell(fill_w - 4, 8, f"{score:.1f} / 10  {label}", align="L")

    pdf.set_y(gauge_y + gauge_h + 4)

    # Tick marks
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*COL_MID_GRAY)
    for tick in range(0, 11, 2):
        tx = gauge_x + int((tick / 10) * gauge_w)
        pdf.set_xy(tx - 3, pdf.get_y())
        pdf.cell(6, 4, str(tick), align="C")
    pdf.ln(6)


# ─────────────────────────────────────────────────────────────────────────────
#  Findings Section
# ─────────────────────────────────────────────────────────────────────────────
def _draw_findings_section(pdf, findings):
    _section_header(pdf, "DETAILED FINDINGS")

    # Group by severity
    severity_order = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    groups = {s: [] for s in severity_order}
    for f in findings:
        sev = f.get("severity", "INFO").upper()
        groups.get(sev, groups["INFO"]).append(f)

    finding_num = 1
    for sev_name in severity_order:
        group = groups[sev_name]
        if not group:
            continue

        sev_col = SEV_COLORS.get(sev_name, (100, 116, 139))
        sev_bg  = SEV_BG.get(sev_name, COL_LIGHT_GRAY)

        # Severity group header page break check
        if pdf.get_y() > 235:
            pdf.add_page()

        pdf.set_fill_color(*sev_bg)
        pdf.set_draw_color(*sev_col)
        pdf.set_line_width(0.3)
        pdf.rect(20, pdf.get_y(), 170, 10, "FD")
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*sev_col)
        pdf.set_x(24)
        pdf.cell(160, 10, f"  {sev_name}  --  {len(group)} finding(s)",
                 align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)

        for f in group:
            _draw_finding_card(pdf, f, finding_num)
            finding_num += 1
            pdf.ln(3)

        pdf.ln(4)


def _draw_finding_card(pdf, finding, num):
    """Draw a single finding card."""
    sev_name = finding.get("severity", "INFO").upper()
    sev_col  = SEV_COLORS.get(sev_name, (100, 116, 139))
    sev_bg   = SEV_BG.get(sev_name, COL_LIGHT_GRAY)
    score    = finding.get("cvss_base_score", 0.0)
    title    = finding.get("title", "Unknown Finding")
    desc     = finding.get("description", "")
    evidence = finding.get("evidence", "")
    tool     = finding.get("tool", "")
    category = finding.get("category", "")
    cve      = finding.get("cve", "")
    vector   = finding.get("cvss_vector", "")

    # Estimate height needed for card to avoid awkward page breaks
    desc_lines = (len(desc) // 65) + 1 if desc else 0
    ev_lines   = (len(evidence) // 65) + 1 if evidence else 0
    est_height = 15 + (desc_lines * 5) + (ev_lines * 4.5) + (4 if vector else 0)

    # Page break check using estimated height
    if pdf.get_y() + est_height > 260:
        pdf.add_page()

    card_x = 20
    start_y = pdf.get_y()

    # Finding number + title
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*COL_TEXT_DARK)
    pdf.set_xy(card_x + 6, start_y + 1)
    title_display = f"#{num:02d}  {title}"
    if len(title_display) > 80:
        title_display = title_display[:77] + "..."
    pdf.cell(120, 6, title_display, align="L")

    # CVSS score badge
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*sev_col)
    pdf.set_text_color(*COL_WHITE)
    pdf.set_xy(card_x + 130, start_y + 1)
    pdf.cell(36, 6, f"CVSS {score:.1f}  {sev_name}", fill=True, align="C",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_y(start_y + 8)

    # Meta row: tool | category | CVE
    meta_parts = [f"Tool: {tool.upper()}"]
    if category:
        meta_parts.append(f"Category: {category}")
    if cve:
        meta_parts.append(f"CVE: {cve}")
    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(*COL_MID_GRAY)
    pdf.set_x(card_x + 6)
    pdf.cell(164, 5, "  |  ".join(meta_parts), align="L",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Description
    if desc:
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(*COL_TEXT_DARK)
        pdf.set_x(card_x + 6)
        desc_display = desc[:300] + ("..." if len(desc) > 300 else "")
        pdf.multi_cell(164, 5, desc_display)

    # Evidence
    if evidence:
        pdf.set_font("Helvetica", "I", 7.5)
        pdf.set_text_color(60, 80, 120)
        pdf.set_x(card_x + 6)
        ev_display = evidence[:150] + ("..." if len(evidence) > 150 else "")
        pdf.multi_cell(164, 4.5, f"Evidence: {ev_display}")

    # CVSS vector (if available)
    if vector:
        pdf.set_font("Helvetica", "I", 7)
        pdf.set_text_color(*COL_MID_GRAY)
        pdf.set_x(card_x + 6)
        pdf.cell(164, 4, f"CVSS Vector: {vector}", align="L",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Calculate actual card height and draw borders / accent
    end_y = pdf.get_y() + 1
    card_h = max(10.0, end_y - start_y) if end_y > start_y else est_height

    # Bottom border line
    pdf.set_draw_color(*sev_col)
    pdf.set_line_width(0.2)
    pdf.line(card_x + 4, end_y, card_x + 170, end_y)

    # Left severity stripe
    pdf.set_fill_color(*sev_col)
    pdf.rect(card_x, start_y, 4, card_h, "F")

    pdf.set_y(end_y + 2)


# ─────────────────────────────────────────────────────────────────────────────
#  Appendix
# ─────────────────────────────────────────────────────────────────────────────
def _draw_appendix(pdf, scan_results, risk_summary):
    _section_header(pdf, "APPENDIX -- SCAN MODULE SUMMARY")

    for tool_name, data in scan_results.items():
        status = data.get("status", "unknown")
        if status == "success":
            status_col = (50, 180, 50)
        elif status == "error":
            status_col = (220, 38, 38)
        else:
            status_col = (200, 150, 0)

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*COL_BG_DARK)
        pdf.set_x(20)
        pdf.cell(0, 7, f"  {tool_name.upper()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Status
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(*COL_TEXT_DARK)
        pdf.set_x(24)
        pdf.set_text_color(*status_col)
        pdf.cell(0, 5, f"Status: {status.capitalize()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Findings count
        n = len(data.get("findings", []))
        pdf.set_text_color(*COL_TEXT_DARK)
        pdf.set_x(24)
        pdf.cell(0, 5, f"Findings: {n}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Extra info per tool
        if tool_name == "nmap" and data.get("open_ports"):
            pdf.set_x(24)
            pdf.cell(0, 5, f"Open Ports: {', '.join(map(str, data['open_ports']))}",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if tool_name == "gobuster" and data.get("paths"):
            pdf.set_x(24)
            pdf.cell(0, 5, f"Paths Discovered: {len(data['paths'])}",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if tool_name == "whatweb" and data.get("technologies"):
            techs = ", ".join(t["name"] for t in data["technologies"][:8])
            pdf.set_x(24)
            pdf.multi_cell(166, 5, f"Technologies: {techs}")

        pdf.set_draw_color(*COL_LIGHT_GRAY)
        pdf.set_line_width(0.3)
        pdf.line(24, pdf.get_y() + 1, 190, pdf.get_y() + 1)
        pdf.ln(4)

    # Disclaimer
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*COL_MID_GRAY)
    disclaimer = (
        "DISCLAIMER: This report was generated by an automated scanning system. "
        "Results may contain false positives. All findings should be manually verified "
        "before remediation. This report is intended for authorized security testing only."
    )
    pdf.multi_cell(0, 5, disclaimer)


# ─────────────────────────────────────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────────────────────────────────────
def _section_header(pdf, title):
    pdf.set_fill_color(*COL_BG_DARK)
    pdf.rect(0, pdf.get_y(), 210, 14, "F")
    pdf.set_fill_color(*COL_ACCENT)
    pdf.rect(0, pdf.get_y(), 5, 14, "F")
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*COL_WHITE)
    pdf.set_x(12)
    pdf.cell(0, 14, title, align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(*COL_TEXT_DARK)
    pdf.ln(5)


def _section_subheader(pdf, title):
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*COL_ACCENT)
    pdf.set_x(20)
    pdf.cell(0, 6, title.upper(), align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(*COL_ACCENT)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 80, pdf.get_y())
    pdf.set_text_color(*COL_TEXT_DARK)
    pdf.ln(3)
